### ISSUE TITLE
type 'Symbol' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub_semver#20]
_From @zoechi on April 3, 2018 8:44_

[pub_upgrade.log](https://github.com/dart-lang/pub/files/1870768/pub_upgrade.log)

Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "macos_x64"

_Copied from original issue: dart-lang/pub#1856_

**Comment by nex3** [comment]
This seems to be caused by a logic bug in this package. We (correctly) consider the version range `<1.0.0` to disallow `1.0.0-dev.1`, but `(<1.0.0).allowsAny(>=1.0.0-dev.1)` returns `true`.

**Comment by grundid** [comment]
I'm still getting this error on Pub 2.0.0-dev.47.0.
Dart VM version: 2.0.0-dev.47.0 (Tue Apr 10 15:09:09 2018 +0200) on "macos_x64"

[pub-trace.log](https://github.com/dart-lang/pub_semver/files/1899108/pub-trace.log)

**Comment by nex3** [comment]
@grundid I can't reproduce that error with Pub 2.0.0-dev.47.0 and the following pubspec:

```yaml
name: angular_dart_demo
version: 0.1.0

dependencies:
  angular_components: ^0.8.0
  angular: ^5.0.0-alpha
  build_runner: ^0.8.2
  test: ^0.12.30
  build_web_compilers: ^0.3.6
  build_test: ^0.10.1
  angular_test: ^2.0.0-alpha
```

**Comment by grundid** [comment]
my config is as follows:

```
name: angular_dart_demo
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.8.0

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.2
  build_test: ^0.10.1
  build_web_compilers: ^0.3.6
  test: ^0.12.30

```  

@nex3 with you config I got the following error, that the resolution does not work due to angular_components < 0.8.0-alpha depending on angular ^4.0.0. Then I updated angular_components to 0.9.0-alpha and now it is working. 
However when I wanted to report this and copy&past the original error message, I cannot reproduce it anymore. Now, when use your config I get the original error. 

[pub-trace.log](https://github.com/dart-lang/pub_semver/files/1901621/pub-trace.log)
